language: node_js
node_js:
  - '8'
branches:
  only:
    - master
    - develop
    - '/^v.*$/'
before_script:
  - npm install
before_deploy:
  - npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: m05Z+SEOQ+zCpL9nVpHiVd4aLrmV02IeRORMFiPibGXpIhjitX51nvDgs28BnDWRI8Pl/C598dz75THgLxTswji6Ik6rE7RM8J/aLg5jFRXkeEag+C5mzY7dId/yuhJSszOxu/srJqZXEotxomBAIOdfu1E+6LJzUA5MJqqve3Zg8VPmC/010tCM2OCkqXzQiOgwnHA60yBBpmGNlx7SQGL++J4l4orOfvFzp0hc26u3paYIHfSXo2BCfrRGAPdkAMGpLR7eT4m/YZZTejuQBQSEUmYzDpfb97g/SVbm+4hqCZp6CEC3KSFuENEgnYb7mMGLeoj8UJKYmrXWJLxgRO68eeoSNhieJJt5B0v0CZJ5C0Tt6+iihTB7OpAvT5NWEg7XaMrjduOaK8dVsINKRM0fRfckjzpvugoNkGMi+MOvu7MgluXihRWQzOGU9xinUVFFc7Vk2NxJzR/E1kZuQAFcTzGvfa6o7/gqGIoQ/JlvuFXDXjFgLfASyCXjsobV8e7acu/I5elr9Y7MaEjhxNayLY09XCxmP8Unx0qqPksxNupFgBfFTbm5sNkj30hRrvw1zCj9IdFjP4/aFjDkSrAd/NoJss3qtiNgbSVCbiol0UQRF2IBu2mOtnw/K9ZiAK0E7MK4qKt0zmm9D75NX86O9ZDUI+5zAPiUIVGQjBw=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: higlass/range-track
  - provider: npm
    skip_cleanup: true
    email: service@lekschas.de
    api_key:
      secure: qlN1V2owhR/VIq4M53Wb7v/KPkv8fVNO/J4lnsAdc2TG41XQjDIdZpQQyA2S4Hqt++qzfLvsZytyfmcEvFdz75dkydP6j4+jgDbrebzPui/+ROwd9KOb+ObQqzF1XNdnlOmLpBIbYqXcPyM+p8EZQlunRYZ/M71R2Z6n/SQHf+0PRrnLk2Jnm/vsFvLqKfpMaPHH/oG6JFIhZSB9A7mJaMMfd6BIgiKCf9jowZjpYcyolxeqiJFWqbUh2Mcy7TFaqIv/J9B+iUa4znSXLyHW2zAstOGKuTSKJC5ucgVZsz8r9iTt6oiKA5gaUByqMyZpuDK8fHDsCcOLU+okDSwhVjBpbQOAtD7pYzyL/ssPEWtnhjuDCMjYWnRmn8M0PNWaN/MPoRLw6L0SiRER13vEVGGid/m/nUD7q9K1MD5lMQnInlu+TtmABmAGJeW+xaGV1abHhLp2RVmsR7YZyDt61A27+f8kUQ+bJzrCtPJSbGgQ/JFRK1GERxIMoqfnipTD3h5/3jHL+VP7r0jSM9g21R4bcNuyHv+Xl7wPBI4nedEYm8SipTfOi3+YkRoyQF4daUZhxeU7J9WVIzdnSWT/Py9kCGTjeMPn9gs+ff/WOO6O4W13KVSBa04PJ5vZhARoI3KuprMPI4i34MS9y6sPcPKkwQlqKERM4x2BOgxwuLk=
    on:
      branch: master
      tags: true
      repo: higlass/range-track
